# Site settings
baseURL = "/"
languageCode = "en-us"
title = "Portfolio for Ted Laderas, PhD"
theme = "forty"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Enter your disqus shortname to enable comments
disqusShortname = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # Provide your metadata here.
  name = "Ted Laderas"
  description = "Portfolio/CV for Ted Laderas"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Just a custom image variable, please define it in .md files for content.
  image = ""

  ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$", "public"]

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Navigation Section
  [params.navigation]
    title = "Ted Laderas, PhD"
    subtitle = "Data Scientist, Educator, and Collaborator"
    menu = "Menu"
    # Optional logo as brand stored in img/
    # logo = "logo.png"

    [[params.navigation.links]]
      name = "Home"
      url = "#"

    [[params.navigation.links]]
      name = "Blog"
      url = "blogs"

    # Add custom links here by uncommenting code below. To remove links just delete
    # the [[params.navigation.links]] map associated with that link. Copy and paste
    # code below if you need more links. Buttons work in the same way.
    # [[params.navigation.links]]
    #    name = "NameOfLink"
    #    url = "UrlOfLink"

    # Button Style 1
    #[[params.navigation.button1]]
    #  name = "Get Started"
    #  url = "blogs"

    # Button Style 2
    #[[params.navigation.button2]]
    #  name = "Log In"
    #  url = "#"


  # Banner section
  [params.banner]
    # To change the background image on the homepage banner, replace 'banner.jpg' in
    # the 'static/img' folder.
    title = "Ted Laderas, PhD"
    subtitle = "Portfolio of Data Science and Visualization Projects"
    buttonText = "Curriculum Vitae"
    url = "cv/"


  # Tiles Section
  [params.tiles]
    enable = true
    # Display your showcases here.
    
    [[params.tiles.showcase]]
      title = "Project: Choropleths of Ready for R Class"
      subtitle = "Where are the Ready for R Students From?"
      image = "projects/choropleth.png"
      url = "projects/choropleth"

    [[params.tiles.showcase]]
      title = "Project: Animal Crossing Tidy Tuesday"
      subtitle = "What personality/animal combos are unique?"
      image = "projects/ac.png"
      url = "projects/animal_crossing"

    [[params.tiles.showcase]]
      title = "Course: Ready for R"
      subtitle = "A gentle introduction to the R and the tidyverse"
      image = "projects/ready4r.png"
      url = "https://ready4r.netlify.app"

    [[params.tiles.showcase]]
      title = "Course: Stats for Neuroscientists"
      subtitle = "A Course on Statistical Image Processing"
      image = "projects/stats4neuro.png"
      url = "https://stats4neuro.netlify.app"
      
    [[params.tiles.showcase]]
      title = "Course: R-Bootcamp"
      subtitle = "An interactive introduction to the tidyverse"
      image = "projects/r-bootcamp.jpg"
      url = "https://r-bootcamp.netlify.app"

    [[params.tiles.showcase]]
      title = "Workshop: A gRadual Introduction to Shiny"
      subtitle = "A short workshop introducing basic shiny programming concepts"
      #image = "projects/r-bootcamp.jpg"
      url = "https://laderast.github.io/gradual_shiny/"

    # You can make more showcases by copy and pasting the code above

  [params.blog]
    # All blogs defined in their own files. You can find example blogs
    # at 'exampleSite/content/blogs'. Copy the 'blogs' folder into the 'content' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    # To add more blogs just copy and paste the code.

  # Section Type Two
  [params.two]
    enable = false
    title = "Massa libero"
    subtitle = """Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero. 
    Mauris aliquet magna magna sed nunc rhoncus pharetra. 
    Pellentesque condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia pellentesque lorem ipsum dolor. 
    Nullam et orci eu lorem consequat tincidunt. Vivamus et sagittis libero.
    Mauris aliquet magna magna sed nunc rhoncus amet pharetra et feugiat tempus."""
    buttonText = "Get Started"
    url = "blogs"


  # Contact section
  [params.contact]
    enable = true
    buttonSend = "Send message"
    buttonClear = "Clear"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below and uncomment
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    # formEmail = "example@domain.com"

    # Contact Section
    # You can add multiple emails, phone numbers, or addresses
    # by copying the corresponding map with frontmatter code.
    [[params.contact.email]]
    title = "Email"
    email = "tedladeras@gmail.com"

    [[params.contact.phone]]
    title = "Phone"
    phone = "(000) 000-0000 x1234"

    [[params.contact.address]]
    title = "Address"
    street = "3181 SW Sam Jackson Road"
    city = "Portland, OR 97212"
    country = "USA"

  # Footer section
  [params.footer]
    enable = true
    copyright = "Ted Laderas"

    # Uses font awesome icons
    [[params.footer.social]]
      icon = "fa-twitter"
      url= "https://www.twitter.com/tladeras"
      label = "Twitter"

    #[[params.footer.social]]
     # icon = "fa-facebook"
      #url= "https://www.facebook.com"
      #label = "Facebook"

    #[[params.footer.social]]
     # icon = "fa-instagram"
      #url= "https://www.instagram.com"
      #label = "Instagram"
    
    [[params.footer.social]]
      icon = "fa-github"
      url= "https://www.github.com/laderast"
      label = "GitHub"

    [[params.footer.social]]
      icon = "fa-linkedin"
      url= "https://www.linkedin.com/in/ted-laderas-0714a92/"
      label = "LinkedIn"

    [[params.footer.quicklinks]]
      text = "Design: "
      url= "https://www.html5up.net"
      alt = "HTML5 UP"
